# Generated by Django 4.2.16 on 2026-05-07 01:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('genero', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1)),
                ('instagram', models.CharField(blank=True, help_text='@usuario', max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmada'), ('E', 'Entregue'), ('X', 'Cancelada')], default='P', max_length=1)),
                ('observacoes', models.TextField(blank=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='perfumes.cliente')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('U', 'Unissex')], max_length=1)),
                ('tamanho_ml', models.IntegerField(choices=[(25, '25ml'), (30, '30ml'), (50, '50ml'), (75, '75ml'), (80, '80ml'), (90, '90ml'), (100, '100ml'), (150, '150ml'), (200, '200ml')])),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfumes', to='perfumes.marca')),
            ],
            options={
                'verbose_name': 'Perfume',
                'verbose_name_plural': 'Perfumes',
                'ordering': ['marca', 'nome', 'tamanho_ml'],
                'unique_together': {('nome', 'marca', 'genero', 'tamanho_ml')},
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('preco_custo', models.DecimalField(decimal_places=2, help_text='Preço de custo na data da venda', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('preco_venda', models.DecimalField(decimal_places=2, help_text='Preço de venda para o cliente', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfumes.perfume')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='perfumes.venda')),
            ],
            options={
                'verbose_name': 'Item da Venda',
                'verbose_name_plural': 'Itens da Venda',
            },
        ),
    ]
