# Generated by Django 2.2.12 on 2022-02-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='fabricante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perfumes.Fabricante'),
            preserve_default=False,
        ),
    ]
