# Generated by Django 2.2.12 on 2022-02-22 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0003_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perfumes.Genero'),
            preserve_default=False,
        ),
    ]
