# Generated by Django 2.2.12 on 2022-02-22 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0007_auto_20220222_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='tamanho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perfumes.Tamanho'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='nome',
            field=models.CharField(max_length=25),
        ),
    ]
