# Generated by Django 2.2.12 on 2022-02-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0010_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(default='2022-02-26'),
            preserve_default=False,
        ),
    ]
