# Generated by Django 2.2.12 on 2022-03-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0012_auto_20220226_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(),
        ),
    ]
