# Generated by Django 2.2.12 on 2022-03-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0014_auto_20220306_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(auto_now=True),
        ),
    ]
