# Generated by Django 2.2.12 on 2022-03-07 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0015_auto_20220306_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfumes.Fabricante'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfumes.Genero'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfumes.Tamanho'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfumes.Tipo'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfumes.Cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfumes.Perfume'),
        ),
    ]
